// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MessageTest.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MessageTest.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MessageTest::MessageTest()
{
    // m_now com.eprosima.idl.parser.typecode.PrimitiveTypeCode@47ef968d
    m_now = 0.0;
    // m_message com.eprosima.idl.parser.typecode.StringTypeCode@3dd4520b
    m_message ="";

}

MessageTest::~MessageTest()
{


}

MessageTest::MessageTest(
        const MessageTest& x)
{
    m_now = x.m_now;
    m_message = x.m_message;
}

MessageTest::MessageTest(
        MessageTest&& x)
{
    m_now = x.m_now;
    m_message = std::move(x.m_message);
}

MessageTest& MessageTest::operator =(
        const MessageTest& x)
{

    m_now = x.m_now;
    m_message = x.m_message;

    return *this;
}

MessageTest& MessageTest::operator =(
        MessageTest&& x)
{

    m_now = x.m_now;
    m_message = std::move(x.m_message);

    return *this;
}

size_t MessageTest::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t MessageTest::getCdrSerializedSize(
        const MessageTest& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;


    return current_alignment - initial_alignment;
}

void MessageTest::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_now;
    scdr << m_message;

}

void MessageTest::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_now;
    dcdr >> m_message;
}

/*!
 * @brief This function sets a value in member now
 * @param _now New value for member now
 */
void MessageTest::now(
        double _now)
{
    m_now = _now;
}

/*!
 * @brief This function returns the value of member now
 * @return Value of member now
 */
double MessageTest::now() const
{
    return m_now;
}

/*!
 * @brief This function returns a reference to member now
 * @return Reference to member now
 */
double& MessageTest::now()
{
    return m_now;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void MessageTest::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void MessageTest::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& MessageTest::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& MessageTest::message()
{
    return m_message;
}

size_t MessageTest::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MessageTest::isKeyDefined()
{
    return false;
}

void MessageTest::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
